'use strict';

import mongoose from 'mongoose';

var ManageclaimSchema = new mongoose.Schema({
  claimRepairHeaderDTO: Object,
  claimSupplementDTO: [],
  tmaDecisionInfoPVO: [],
  claimJobTypes: [],
  selectedClaimJobs: [],
  allMINames: [],
  casenoSourceList: [],
  appealStateList: [],
  claimValidationErrorTextDTOList: [],
  vehicleOperationAuths: [],
  workingWithSelectedClaimJobs: Boolean,
  activeTab: String,
  matchedInspectorReport: Object,
  matchedInspectorReportList: [],
  inspectorReportAndVehicleMap: String,
  activeJobHasErrors: Boolean,
  activeJobIdFromVerticalTab: String,
  jobListSize: Number,
  labourTabLoaded: Boolean,
  claimJobInfoTabLoaded: Boolean,
  remarksTabLoaded: Boolean,
  assessmentMode: String,
  assessmentCostType: Number,
  rejectedDebitCodes: String,
  disableVehicleInfo: Boolean,
  popupClaim: Boolean,
  supplementChanged: Boolean,
  claimChanged: Boolean,
  noChange: Boolean,
  warningFlag: Boolean,
  campaign: Object,
  selectedCausalPartId: String,
  technicalDataUrl: String,
  technicalDataUrl2: String,
  uchpCampaignVehicleMaster: Boolean,
  allowCopyClaimJob: Boolean,
  viewCampaignUrl: String,
  applyVATBasedOnMaterial: Boolean,
  dbAssessmentDTO: Object,
  inspectorReportStatuses: [],
  companyList: [],
  makeList: [],
  mileageUnitList: [],
  yesNoList: [],
  otherCostCategoryList: [],
  copyClaimJobNO: String,
  copyClaimRefNO: String,
  defaultPartNoPrefix: String,
  selectedClaimJobType: String,
  newClaimJob: Boolean
});

export default mongoose.model('Manageclaim', ManageclaimSchema);
